language: python
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python: "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install nose"

script:
  - "nosetests ubio/"

deploy:
  - provider: script
    skip_cleanup: true
    script: fab update --envtype=staging
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: fab update --envtype=production
    on:
      branch: release
