# Generated by Django 2.1.7 on 2019-03-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='original_avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
