# Generated by Django 2.1.7 on 2019-03-20 11:22

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_original_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='original_avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=profiles.models.get_avatar_full_path),
        ),
    ]
